name = ai_players
title = AI Players for luanti
description = My first mod with AI Players that build, talk and mine, also with portable afk farms blocks
author = Jazzlagamer
version = 2.0
optional_depends = player_api, default
